#' Call python code to generate k-mer of training dataset.
#' @param K the number of k, k-mer.
loadDataset <- function(K){
  # Set Python3 path.
  exePythonPath = sprintf("/usr/local/bin/python3 src/output-train-dataset.py %d", K)
  # Execute python code and generate k-mer dataset.
  system(exePythonPath)

  # Load dataset.
  cat("# Loading CSV file...\n")
  data.csv <- read.csv("tmpdata/dataset.csv", header = FALSE, stringsAsFactors=FALSE)
  data <- unname(as.matrix(data.csv))
  length <- read.csv("tmpdata/length.csv", header = FALSE, stringsAsFactors=FALSE)
  length <-as.numeric(unname(as.matrix(length)))
  datalist <- read.csv("tmpdata/datalist.csv", header = FALSE, stringsAsFactors=FALSE)
  datalist <- unname(as.matrix(datalist))

  # Store labels.
  labels <- NULL
  for(i in 1:length(length)){
    labels <- c(labels, rep(as.character(i),length[i]))
  }

  return(list(data=data, labels=labels, data.length=length, datalist=datalist))
}

#' Call python code to generate k-mer of test dataset.
#' @param K the number of k, k-mer.
loadTestDataset <- function(K){
  # Set Python3 path.
  exePythonPath = sprintf("/usr/local/bin/python3 ../src/output-test-dataset.py %d", K)
  # Execute python code and generate k-mer dataset.
  system(exePythonPath)

  # Load dataset.
  cat("# Loading CSV file...\n")
  data.csv <- read.csv("tmpdata/dataset.csv", header = FALSE, stringsAsFactors=FALSE)
  data <- unname(as.matrix(data.csv))
  length <- read.csv("tmpdata/length.csv", header = FALSE, stringsAsFactors=FALSE)
  length <-as.numeric(unname(as.matrix(length)))
  dataid <- read.csv("tmpdata/geneid.csv", header = FALSE, stringsAsFactors=FALSE)
  dataid <- unname(as.matrix(dataid))

  # Store labels.
  labels <- NULL
  for(i in 1:length(length)){
    labels <- c(labels, rep(as.character(i),length[i]))
  }

  return(list(data=data, labels=labels, data.length=length, id=dataid))
}

#' Adjust the dataset sample size to an arbitrary number of sample size.
#' @param dataset k-mer dataset list generated by loadDataset.
fitSampleSize <- function(dataset, maxSize){
  allExtractIndex <- NULL
  endpoint <- 0
  for(i in 1:length(dataset$data.length))
  {
    sampleLengths <- dataset$data.length[i]
    if(maxSize < sampleLengths){
      extractIndex <- sample(1:sampleLengths, maxSize)
    }else{
      extractIndex <- sample(1:sampleLengths, sampleLengths)
    }

    allExtractIndex <- c(allExtractIndex, extractIndex  + endpoint)
    endpoint <- endpoint + sampleLengths
  }

  data <- dataset$data[allExtractIndex, ]
  labels <- dataset$labels[allExtractIndex]

  return(list(data=data, labels=labels))
}

#' Calculate macro precision and recall
#' @param confusion_matrix a confusion matrix
calc_precision_recall <- function(confusion_matrix){
  dim <- ncol(confusion_matrix)
  tp_list <- numeric(dim)
  fp_list <- numeric(dim)
  fn_list <- numeric(dim)
  
  for(i in 1:dim){
    tp_list[i] <- confusion_matrix[i,i]
    fp_list[i] <- sum(confusion_matrix[i,-i])
    fn_list[i] <- sum(confusion_matrix[-i,i])
  }
  macro_precision <- 0
  macro_recall <- 0
  for(i in 1:dim){
    macro_precision <- macro_precision + tp_list[i]/(tp_list[i] + fp_list[i])
    macro_recall <- macro_recall + tp_list[i]/(tp_list[i] + fn_list[i])
  }
  macro_precision <- macro_precision/dim
  macro_recall <- macro_recall/dim
  
  return(list(precision=macro_precision, recall=macro_recall))
}

#' Generator k-mer name list
#' @param K the number of k, k-mer.
K_mer_name_list <- function(K){
  seq <- c("A", "T", "G", "C")
  Stock <- NULL
  if(K == 2)
  {
    for(i in 1:4)
    {
      for(ii in 1:4)
      {
        Stock <- c(Stock, paste(seq[i], seq[ii], sep=""))
      }
    }
  }
  if(K == 3)
  {
    for(i in 1:4)
    {
      for(ii in 1:4)
      {
        for(iii in 1:4)
        {
          Stock <- c(Stock, paste(seq[i], paste(seq[ii], seq[iii], sep=""), sep=""))
        }
      }
    }
  }
  if(K == 4)
  {
    for(i in 1:4)
    {
      for(ii in 1:4)
      {
        for(iii in 1:4)
        {
          for(iiii in 1:4)
          {
            Stock <- c(Stock, paste(seq[i],paste(seq[ii], paste(seq[iii], seq[iiii], sep=""), sep=""), sep=""))
          }
        }
      }
    }
  }
  if(K == 5)
  {
    for(i in 1:4)
    {
      for(ii in 1:4)
      {
        for(iii in 1:4)
        {
          for(iiii in 1:4)
          {
            for(iiiii in 1:4)
            {
              Stock <- c(Stock, paste(seq[i],paste(seq[ii],paste(seq[iii], paste(seq[iiii], seq[iiiii], sep=""), sep=""), sep=""), sep=""))
            }
          }
        }
      }
    }
  }
  return(Stock)
}
